update
LWHK/Wizardry pull request #2
Opened 2021-02-03 06:40 UTC by TUsama

2021-02-03 06:42 UTC, TUsama commented
@Determancer

2021-02-03 07:24 UTC, Determancer requested changes

2021-02-03 07:24 UTC, Determancer commented on src/main/resources/assets/ebwizardry/texts/handbook_zh_cn.json
> +				"穷其一生求知若渴，贤者在施法效率一途已臻于巅峰，他们能以最小量的魔力施放法术。丝绸长袍的华美掩盖了其强大的防护能力，要知道，贤者同样是娴熟的附魔者——只不过，这些长袍依然无法与坚固的金属板相匹敌。同时，长时间待在实验室中固然安逸，但也让他们在战斗中显得无比笨拙。",
兄啊，这是`library`，不是`laboratory`。
“笨拙”意义较宽泛，原文`sluggish`偏向于强调“慢”。
```suggestion
				"穷其一生求知若渴，已使贤者在高效施法的技艺上臻于巅峰，他们能以最小量的魔力施放法术。贤者们所着丝绸长袍的华美掩盖了其强大的防护能力，要知道，贤者同样是娴熟的附魔者——只不过，这些长袍依然无法与坚固的金属板相匹敌。同时，长时间待在图书馆中固然安逸，但也让他们在战斗中显得无比迟缓。",
```

2021-02-03 07:24 UTC, Determancer commented on src/main/resources/assets/ebwizardry/texts/handbook_zh_cn.json
> +				"战斗巫师披铠待战，所着铠甲由技艺炉火纯青的锻造厂打造，内为坚韧布匹，外镶晶银镶板。在经历了刻苦的训练后 ，他们的速度与反应力都有了一定提升，因而他们能够更频繁的施放法术。然而，频繁施法的代价同样高昂，战斗巫师在战斗中得小心，别过快的把魔力耗光了。",
物品名已经是战斗法师了，干脆统一一下。
```suggestion
				"战斗法师",

				"战斗法师披铠待战，所着铠甲由技艺炉火纯青的锻造厂打造，内为坚韧布匹，外镶晶银镶板。在经历了刻苦的训练后，他们的速度与反应力都有了一定提升，因而他们能够更频繁地施放法术。然而，频繁施法的代价同样高昂，战斗法师在战斗中得小心，以免过快地耗尽魔力。",
```

2021-02-03 07:24 UTC, Determancer commented on src/main/resources/assets/ebwizardry/texts/handbook_zh_cn.json
> +				"巫术师为探险而生，他们探寻失落的奥术秘密，不断推进那已知与未知之间的界限。此外，他们还愿意去尝试那些被人们视为蛇蝎的禁忌之物， 这种种原因使得他们能够突破传统训练的限制，以惊人的速度施放法术，并且减少魔力的使用量。他们的长袍十分轻盈，这对探险颇为有益，但相对应的，这种长袍的防护能力羸弱异常，在三种流派中排在最后一位。"
物品名已经是巫术士了，干脆统一一下。再者，巫术师和巫师重字率过高。
`counterparts`指的是三个流派，此处的“但相对应的”属于重复翻译。
“羸弱”常用于形容体质。且原文仅强调了`less`，并无**异常脆弱**的意思。
```suggestion
				"巫术士",

				"巫术士为求索而生，他们不断推进那已知与未知之间的界限，探寻失落的奥术秘密。此外，他们还愿意去尝试那些被人们视若蛇蝎的禁忌法术，这种种原因使得他们能够突破传统训练的限制，以惊人的速度施放法术，并且减少魔力的使用量。他们的长袍十分轻盈，这对探险颇为有益，但与此同时，这种长袍的防护能力在三种流派的巫师盔甲中最为脆弱。"
```

2021-02-03 07:35 UTC, TUsama commented on src/main/resources/assets/ebwizardry/texts/handbook_zh_cn.json
> +				"穷其一生求知若渴，贤者在施法效率一途已臻于巅峰，他们能以最小量的魔力施放法术。丝绸长袍的华美掩盖了其强大的防护能力，要知道，贤者同样是娴熟的附魔者——只不过，这些长袍依然无法与坚固的金属板相匹敌。同时，长时间待在实验室中固然安逸，但也让他们在战斗中显得无比笨拙。",
艹

2021-02-03 07:36 UTC, TUsama commented on src/main/resources/assets/ebwizardry/texts/handbook_zh_cn.json
> +				"战斗巫师披铠待战，所着铠甲由技艺炉火纯青的锻造厂打造，内为坚韧布匹，外镶晶银镶板。在经历了刻苦的训练后 ，他们的速度与反应力都有了一定提升，因而他们能够更频繁的施放法术。然而，频繁施法的代价同样高昂，战斗巫师在战斗中得小心，别过快的把魔力耗光了。",
看歪了

2021-02-03 07:38 UTC, TUsama commented on src/main/resources/assets/ebwizardry/texts/handbook_zh_cn.json
> +				"巫术师为探险而生，他们探寻失落的奥术秘密，不断推进那已知与未知之间的界限。此外，他们还愿意去尝试那些被人们视为蛇蝎的禁忌之物， 这种种原因使得他们能够突破传统训练的限制，以惊人的速度施放法术，并且减少魔力的使用量。他们的长袍十分轻盈，这对探险颇为有益，但相对应的，这种长袍的防护能力羸弱异常，在三种流派中排在最后一位。"
能力...脆弱
缩句之后就看到问题了。

2021-02-03 08:49 UTC, WuzgXY-GitHub requested changes

2021-02-03 08:49 UTC, WuzgXY-GitHub commented on src/main/resources/assets/ebwizardry/texts/handbook_zh_cn.json
> +				"你可以用附魔台为巫师护具附魔,而因为魔法绸缎的固有属性，它们倾向于被附魔上能够使它们留存的更久的附魔。一些附魔，例如魔法，冰霜，雷电保护附魔，对巫师具有特殊的实用价值，这些附魔可以有效抵御其它巫师对你发起的进攻。",
|Feedback Priority|
|---|
|⚪️ Pebble / Non-blocking but requires future action|

```suggestion
				"你可以用附魔台为巫师护具附魔，而因为魔法绸缎的固有属性，它们倾向于得到能使它们留存更久的附魔。一些附魔，例如魔法、冰霜、雷电保护附魔，对巫师具有特殊的实用价值，这些附魔可以有效抵御其他巫师对你发起的进攻。",
```

2021-02-03 08:49 UTC, WuzgXY-GitHub commented on src/main/resources/assets/ebwizardry/texts/handbook_zh_cn.json
> +				"你可以用附魔台为巫师护具附魔,而因为魔法绸缎的固有属性，它们倾向于被附魔上能够使它们留存的更久的附魔。一些附魔，例如魔法，冰霜，雷电保护附魔，对巫师具有特殊的实用价值，这些附魔可以有效抵御其它巫师对你发起的进攻。",
```suggestion
				"你可以用附魔台为巫师护具附魔，而因为魔法绸缎的固有属性，它们倾向于得到能使它们留存更久的附魔。一些附魔，例如魔法、冰霜、雷电保护，对巫师具有特殊的实用价值，这些附魔可以有效抵御其他巫师对你发起的进攻。",
```

2021-02-03 08:49 UTC, WuzgXY-GitHub commented on src/main/resources/assets/ebwizardry/texts/handbook_zh_cn.json
> +				"当巫师们将基础魔法运用自如后，他们会选择某条道路，或者说，流派，来继续增进自身的技艺。他们有三种选择：贤者，战斗巫师以及巫术师。不同学派的成员会选择对原先的基础长袍进行改造，这样可以让长袍更为适应自身所需。因而不同流派的成员之间，所着长袍的样式各有其特点，他们唯一的相同之处便是：修改长袍往往需要一些来自异域的珍稀材料。",
|Feedback Priority|
|---|
|⚪️ Pebble / Non-blocking but requires future action|

```suggestion
				"在巫师们将基础魔法运用自如后，他们会选择某条道路——犹言流派——来继续增进自己的技艺。他们有三种选择：贤者，战斗巫师以及巫术师。不同流派的成员会选择对原先的基础长袍进行改造，这可以让长袍更适应自身所需。因而不同流派的成员所着长袍的样式各异，它们唯一的相同之处是需要用来自异域的珍稀材料修改。",
```

2021-02-03 08:49 UTC, WuzgXY-GitHub commented on src/main/resources/assets/ebwizardry/texts/handbook_zh_cn.json
> +				"穷其一生求知若渴，已使贤者在高效施法的技艺上臻于巅峰，他们能以最小量的魔力施放法术。贤者们所着丝绸长袍的华美掩盖了其强大的防护能力，要知道，贤者同样是娴熟的附魔者——只不过，这些长袍依然无法与坚固的金属板相匹敌。同时，长时间待在图书馆中固然安逸，但也让他们在战斗中显得无比迟缓。",
|Feedback Priority|
|---|
|⚪️ Pebble / Non-blocking but requires future action|

```suggestion
				"穷其一生求知若渴，已使贤者在高效施法的技艺上臻于巅峰，他们能以最小量的魔力施放法术。贤者们所着丝绸长袍的华美掩盖了其强大的防护能力，要知道，贤者同样是娴熟的附魔者——只不过，这些长袍依然无法与坚固的金属板相匹敌。同时，长时间待在图书馆中固然安逸，但也让他们在战斗中显得有些迟缓。",
```

2021-02-03 08:49 UTC, WuzgXY-GitHub commented on src/main/resources/assets/ebwizardry/texts/handbook_zh_cn.json
> +				"战斗法师披铠待战，所着铠甲由技艺炉火纯青的锻造厂打造，内为坚韧布匹，外镶晶银镶板。在经历了刻苦的训练后，他们的速度与反应力都有了一定提升，因而他们能够更频繁地施放法术。然而，频繁施法的代价同样高昂，战斗法师在战斗中得小心，以免过快地耗尽魔力。",
|Feedback Priority|
|---|
|⚪️ Pebble / Non-blocking but requires future action|

```suggestion
				"战斗法师披铠待战，所着铠甲由技艺炉火纯青的锻造厂打造，内为坚韧布匹，外覆晶银镶板。在经历了刻苦的训练后，他们的速度与反应力都有了一定提升，因而他们能够更频繁地施放法术。然而，频繁施法的代价同样高昂，战斗法师在战斗中得小心，以免过早耗尽魔力。",
```

2021-02-03 08:49 UTC, WuzgXY-GitHub commented on src/main/resources/assets/ebwizardry/texts/handbook_zh_cn.json
> +				"巫术士为求索而生，他们不断推进那已知与未知之间的界限，探寻失落的奥术秘密。此外，他们还愿意去尝试那些被人们视若蛇蝎的禁忌法术，这种种原因使得他们能够突破传统训练的限制，以惊人的速度施放法术，并且减少魔力的使用量。他们的长袍十分轻盈，这对探险颇为有益，但与此同时，这种长袍的防御力在三种流派的巫师盔甲中是最低的。"
|Feedback Priority|
|---|
|⚪️ Pebble / Non-blocking but requires future action|

```suggestion
				"巫术士为求索而生，他们不断推进那已知与未知之间的界限，探寻失落的奥术秘密。此外，他们还愿意去尝试那些被人们视若蛇蝎的禁忌法术，这种种原因使得他们能够突破传统训练的限制，以惊人的速度施放法术，并且减少魔力的使用量。他们的长袍十分轻盈，这对探险而言颇有益处，但与此同时，这种长袍的防御力在三个流派的巫师盔甲中是最低的。"
```

2021-02-03 08:49 UTC, WuzgXY-GitHub commented on src/main/resources/assets/ebwizardry/texts/handbook_zh_cn.json
> +						"这些结构大致可分为两类。第一个，也是最常见的，是方尖碑：符文石制成的尖顶，底部有一个开放的结构，其中为次级魔法遗迹，你在上面还能感受到残存着的气息，那是来自被遗忘的过去。",
|Feedback Priority|
|---|
|⚪️ Pebble / Non-blocking but requires future action|

很生硬，且一逗到底，但我也不会改。只有最后一个分句必须作改动

2021-02-03 10:30 UTC, Determancer commented on src/main/resources/assets/ebwizardry/texts/handbook_zh_cn.json
> +				"当巫师们将基础魔法运用自如后，他们会选择某条道路，或者说，流派，来继续增进自身的技艺。他们有三种选择：贤者，战斗巫师以及巫术师。不同学派的成员会选择对原先的基础长袍进行改造，这样可以让长袍更为适应自身所需。因而不同流派的成员之间，所着长袍的样式各有其特点，他们唯一的相同之处便是：修改长袍往往需要一些来自异域的珍稀材料。",
```suggestion
				"在巫师们将基础魔法运用自如后，他们会选择某条道路，或者说是流派，来继续增进自己的技艺。共有三种流派可供选择：贤者，战斗法师以及巫术士。通过长袍的样式可以轻易分辨不同流派的成员，而他们往往会使用奇异而罕见的材料对基础的长袍进行调整，以使其更好地满足自身需求。",
```

2021-02-03 10:33 UTC, Determancer commented on src/main/resources/assets/ebwizardry/texts/handbook_zh_cn.json
> +				"战斗法师披铠待战，所着铠甲由技艺炉火纯青的锻造厂打造，内为坚韧布匹，外镶晶银镶板。在经历了刻苦的训练后，他们的速度与反应力都有了一定提升，因而他们能够更频繁地施放法术。然而，频繁施法的代价同样高昂，战斗法师在战斗中得小心，以免过快地耗尽魔力。",
```suggestion
				"战斗法师披铠待战，所着铠甲由技艺炉火纯青的锻造厂打造，内为坚韧布匹，外覆晶银镶板。在经历了刻苦的训练后，他们的速度与反应力都有了一定提升，因而他们能够更频繁地施放法术。然而，频繁施法的代价同样高昂，战斗法师在战斗中得小心，以免过快地耗尽魔力。",
```

2021-02-03 10:42 UTC, Determancer commented on src/main/resources/assets/ebwizardry/texts/handbook_zh_cn.json
> +						"这些结构大致可分为两类。第一个，也是最常见的，是方尖碑：符文石制成的尖顶，底部有一个开放的结构，其中为次级魔法遗迹，你在上面还能感受到残存着的气息，那是来自被遗忘的过去。",
```suggestion
						"这些结构大致可分为两类。第一个，也是最常见的，是方尖碑：一种高大的锥状构造，由被称为符文石的凿饰石块组成，其底部有一个敞开的结构，里面存放着来自尘封过往的奥术遗物。",
```

2021-02-04 02:40 UTC, TUsama commented on src/main/resources/assets/ebwizardry/texts/handbook_zh_cn.json
> +						"这些结构大致可分为两类。第一个，也是最常见的，是方尖碑：符文石制成的尖顶，底部有一个开放的结构，其中为次级魔法遗迹，你在上面还能感受到残存着的气息，那是来自被遗忘的过去。",
这一段是我出到时候翻译的。

2021-02-04 03:53 UTC, Determancer commented on src/main/resources/assets/ebwizardry/texts/handbook_zh_cn.json
> +				"在巫师们将基础魔法运用自如后，他们会选择某条道路，或者说是流派，来继续增进自己的技艺。共有三种流派可供选择：贤者，战斗法师以及巫术士。通过长袍的样式可以轻易分辨不同流派的成员，因为他们往往会使用奇异而珍稀的材料对基础的长袍进行调整，以使其更好地满足自身需求。",
```suggestion
				"在巫师们将基础魔法运用自如后，他们会选择某条道路，或者说是流派，来继续增进自己的技艺。共有三种流派可供选择：贤者，战斗法师以及巫术士。通过长袍的样式可以轻易分辨不同流派的成员，而他们往往会使用奇异而珍稀的材料对基础的长袍进行调整，以使其更好地满足自身需求。",
```

2021-02-04 04:11 UTC, WuzgXY-GitHub approved these changes

2021-02-04 04:11 UTC, Determancer approved these changes

2021-02-04 05:06 UTC, merged